# general settings
# name: ORCA_synvid (lOw-Rank and flow-guided Conditional prompt for videA restoration)
# name: ORCAtask3
name: ORCAtask3_DAVIS
model_type: VideoRecurrentModel
scale: 1
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Task3Dataset
    type: CTUDVideoDataset
    task: task3
    scale: 1
    dataroot_gt: data/tvddata_DAVIS/train-GT # The dataroot of GT frames
    dataroot_lq: data/tvddata_DAVIS/train-degvid # The dataroot of LQ frames
    meta_info_file: basicsr/data/meta_info/DAVIS_meta_info.txt # The path of video meta information
    io_backend:
      type: disk

    gt_size: 256
    filename_ext: jpg
    filename_tmpl: 05d
    num_frame: 12
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    test_mode: false

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Task3Dataset
    type: VideoRecurrentTestDataset
    task: task3
    dataroot_gt: data/tvddata_DAVIS/valatest-GT
    dataroot_lq: data/tvddata_DAVIS/valatest-degvid

    cache_data: false
    # cache_data: true
    io_backend:
      type: disk

    num_frame: -1

# network structures
network_g:
  type: ORCANet
  # type: AverNet_Unroll
  mid_channels: 32
  prompt_dim: 96
  prompt_size: 96
  num_blocks: 1
  keyframe_interval: 6
  spynet_pretrained: experiments/pretrained_models/pre_flownet/spynet_sintel_final-3d2a1287.pth
# python scripts/data_preparation/generate_meta_info.py --dataset_path DATASETREVID/Train/hazy
# path
path:
  experiments_root: ~
  pretrain_network_g: experiments/ORCAtask1/models/net_g_400000.pth
  strict_load_g: false
  resume_state: experiments/ORCAtask3_DAVIS/training_states/400000.state
  # resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.25

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

  beta:
    type: BetaMSELoss
    loss_weight: 0.5
    reduction: mean

  prompt:
    type: PromptMetricLoss
    tau_pos: 0.7
    tau_neg: 0.4
    margin: 0.5
    loss_weight: 0.02
    reduction: mean

# validation settings
val:
  val_freq: !!float 200000
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr
    ssim:
      type: ssim

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True